/**
 * Created by Max on 2/1/2018.
 */


export const ADD_CHECKOUT_NUMBER = 'ADD_CHECKOUT_NUMBER';
export const FETCH_CHECKOUT_NUMBER = 'FETCH_CHECKOUT_NUMBER';
export const UPDATE_CHECKOUT_NUMBER = 'UPDATE_CHECKOUT_NUMBER';
export const UPDATE_MULTIPLIER = 'UPDATE_MULTIPLIER';
export const UPDATE_SELECTION = 'UPDATE_SELECTION';
export const SUBMIT_BUTTON_PRESSED = 'SUBMIT_BUTTON_PRESSED';
export const UPDATE_SELECTIONS_MADE = 'UPDATE_SELECTIONS_MADE';
export const UPDATE_TURNS = 'UPDATE_TURNS';
export const CLEAN_STATE = 'CLEAN_STATE';
export const CLEAN_STATE_CHECKOUT = 'CLEAN_STATE_CHECKOUT';
export const FETCH_SELECTION_DATA ='FETCH_SELECTION_DATA';
export const GAME_MODE = 'GAME_MODE';





